version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_DB: next_db
      POSTGRES_USER: next_user
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: next_db
    environment:
      POSTGRES_DB: next_db
      POSTGRES_USER: next_user
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "42443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./docker/nginx/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - web
    networks:
      - app-network

volumes:
  db-data:


networks:
  app-network:
    driver: bridge
